### ISSUE TITLE
Resource Module: Calendar Picker for Orders Sub Menu isn't sized correctly and doesn't adjust when the window size changes

### ISSUE THREAD

**Issue by LibrarianMike** [stephanieleary/coral-a11y-cleanup-2024#19] opened 2024-11-26 17:10 UTC
![Order Date Picker issue](https://github.com/user-attachments/assets/c63619c5-aeb5-4264-8fd6-e4a8149b2c98)

The Date Box is not appropriately sized and the date picker icon intrudes into the date box.

**Comment by stephanieleary** [comment] 2024-12-10 17:46
Duplicate of #8.

**Closed as completed by stephanieleary** 2024-12-10 17:46 UTC
